import type { Project, Shot } from "./types";

const shots: Shot[] = [
  {
    id: "shot_1",
    slate: "01-A",
    title: "Cold open",
    caption: "",
    durationMs: 2600,
    locked: false,
    plate: "black",
  },
  {
    id: "shot_2",
    slate: "02-A",
    title: "The landfill",
    caption: "Your context is a landfill.",
    durationMs: 2800,
    locked: false,
    plate: "landfill",
  },
  {
    id: "shot_3",
    slate: "03-A",
    title: "Product in hand",
    caption: "One cut. The question stays.",
    durationMs: 2600,
    locked: false,
    plate: "hand",
  },
  {
    id: "shot_4",
    slate: "04-A",
    title: "The slash",
    caption: "72% smaller. Same answer.",
    durationMs: 2400,
    locked: false,
    plate: "cut",
  },
  {
    id: "shot_5",
    slate: "05-A",
    title: "The laugh",
    caption: "Keep the laugh.",
    durationMs: 3000,
    locked: true,
    plate: "laugh",
  },
  {
    id: "shot_6",
    slate: "06-A",
    title: "Proof",
    caption: "Tokens back. Nerve intact.",
    durationMs: 2400,
    locked: false,
    plate: "proof",
  },
  {
    id: "shot_7",
    slate: "07-A",
    title: "Founder",
    caption: "Cut it with me.",
    durationMs: 2200,
    locked: false,
    plate: "face",
  },
  {
    id: "shot_8",
    slate: "08-A",
    title: "End card",
    caption: "SLATE · a cut you can hold",
    durationMs: 2600,
    locked: false,
    plate: "card",
  },
];

export function sampleProject(): Project {
  return {
    title: "NORTHWIND",
    brief: "Cut a launch under thirty seconds. Keep the laugh. Trim and caption unlocked shots. Export only after the clap.",
    shots,
    selectedId: "shot_1",
    playheadMs: 0,
    playing: false,
    exportArmed: false,
    lastCut: null,
    agent: {
      name: "Codex",
      lastTool: null,
      lastResult: null,
      lastAt: null,
      targetShotId: null,
    },
    history: [],
    future: [],
    nextSeq: 9,
  };
}
